### ISSUE TITLE
Code is incomplete?

### ISSUE THREAD

**Issue by Arsiuuu** [joonholee-research/MUDA#1]
Thanks for the inspiring idea！I want to ask if the experimental code is incomplete，because I only see "svhn2mnist.py", not Office-31,etc.
Looking forward to the answer...

**Comment by joonholee-research** [comment]
> Thanks for the inspiring idea！I want to ask if the experimental code is incomplete，because I only see "svhn2mnist.py", not Office-31,etc. Looking forward to the answer...

Thanks for your interest in this repo. The uploaded *svhn2mnist.py* is excerpted from a complex experimental code but covers the complete experimental procedures. For other protocols, you could easily implement experimental code using the provided codes in *module*.

**Comment by joonholee-research** [comment]
> Thanks for the inspiring idea！I want to ask if the experimental code is incomplete，because I only see "svhn2mnist.py", not Office-31,etc. Looking forward to the answer...

Thanks for your interest in this repo. The uploaded *svhn2mnist.py* is excerpted from a complex experimental code but covers the complete experimental procedures. For other protocols, you could easily implement experimental code using the provided codes in *module*.
